title: SAP First
why: We want standardize your core systems and use the SAP as standard
how: Identify the business capabilities of the planned project. Check in solution target landscape which target solution supports your business capabilities.
validation: Add the planned application including the relationship to the business capabilities.
links:
  - SAP Reference Model: https://www.sap.com/
